"""Emit `perm_forward.cuh` — the c_PERM table (inverse of c_PERM_INV).

For D.2-FIX-v2: when the cp.async loader writes qh data into SMEM, we want to
ALSO precompute the unpacked nibbles for each (k_pair, n_inner) coordinate.
The unpack pass currently does:
    for (k_pair, n_inner) in pairs:
        permuted = c_PERM_INV[orig_flat(k_pair, n_inner)]   # → qh_int_idx, bit_off
        nib = (sh_B_qh[qh_int_idx] >> bit_off) & 0x3

The fix flips this: instead of looping over pairs and looking up qh_int_idx,
loop over qh ints (contiguous SMEM reads = no bank conflict) and write the
extracted nibbles to the unpacked layout. That requires the FORWARD permutation:
given (qh_int_idx, bit_off_pair), find the (k_inner, n_inner) coordinate.

c_PERM[permuted] = orig_flat
where orig_flat = n_tile_id * 256 + k_inner_in_kf * 16 + n_in_tile.

Run once to regenerate; result is checked into the tree alongside perm_inverse.cuh.
"""
from __future__ import annotations

import sys
from pathlib import Path

THIS = Path(__file__).resolve().parent
REPO_ROOT = THIS.parent.parent
sys.path.insert(0, str(REPO_ROOT))

from tools.gguf_vendor.basiwan_q4_kernel.basiwan_perms import get_perms  # noqa: E402


def main():
    perm, _scale_perm, _scale_perm_single = get_perms()
    assert perm.numel() == 1024, f"expected 1024 elements, got {perm.numel()}"

    # perm[j] = i means: the element ORIGINALLY at position i landed at position j
    # after permutation. So c_PERM[j] = i (the forward direction we need).
    c_perm = [int(perm[j].item()) for j in range(1024)]

    # Sanity check: c_PERM and c_PERM_INV should be true inverses.
    # c_PERM_INV[c_PERM[j]] == j for all j.
    perm_inv = [0] * 1024
    for j in range(1024):
        perm_inv[c_perm[j]] = j
    for j in range(1024):
        assert perm_inv[c_perm[j]] == j, f"inverse check failed at j={j}"

    out_path = THIS / "perm_forward.cuh"
    lines = [
        "// AUTO-GENERATED by gen_perm_forward.py — do not edit by hand.",
        "//",
        "// c_PERM[permuted] = orig_flat",
        "// where orig_flat = n_tile_id * 256 + k_inner_in_kf * 16 + n_in_tile.",
        "//",
        "// Used by D.2-FIX-v2 to iterate over qh ints in SMEM (contiguous, no",
        "// bank conflict) and write extracted nibbles to sh_B_qh_unpacked at the",
        "// (k_pair, n_inner) coordinate decoded from c_PERM.",
        "//",
        "// 1024 ints = 4 KB; shares the __constant__ memory pool with c_PERM_INV.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace marlin_v2 {",
        "",
        "__device__ __constant__ uint32_t c_PERM[1024] = {",
    ]
    for chunk_start in range(0, 1024, 8):
        chunk = c_perm[chunk_start:chunk_start + 8]
        lines.append("    " + ", ".join(f"{v:4d}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace marlin_v2")
    lines.append("")
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}  ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
