"""Emit `perm_inverse.cuh` — the constant lookup table the CUDA kernel needs to
invert pack.py's _PERM. Run once to regenerate; result is checked into the tree.

The kernel needs: given a logical (k_inner, n_inner, n_tile_id) position inside
a (k_tile_row, BLOCK_N*16) chunk, locate the position in the _PERM-permuted
packed array. That's the inverse of pack.py's `w[:, _PERM]` step.

BLOCK_N=64 means BLOCK_N*16 = 1024 = exactly one _PERM chunk per K-tile row,
which keeps the indexing local.
"""
from __future__ import annotations

import sys
from pathlib import Path

# So the module imports work when run as a script:
THIS = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS.parent.parent.parent))

from tools.gguf_vendor.basiwan_q4_kernel.basiwan_perms import get_perms


def main():
    perm, _scale_perm, _scale_perm_single = get_perms()
    assert perm.numel() == 1024, f"expected 1024 elements, got {perm.numel()}"

    # _PERM_INV[i] = j  where  _PERM[j] = i
    # Meaning: the element that ORIGINALLY lived at position i is, after permutation,
    # at position _PERM_INV[i] in the packed array.
    perm_inv = [0] * 1024
    for j in range(1024):
        perm_inv[int(perm[j].item())] = j

    out_path = THIS / "perm_inverse.cuh"
    lines = [
        "// AUTO-GENERATED by gen_perm_header.py — do not edit by hand.",
        "//",
        "// _PERM_INV[i] = j where pack.py's _PERM[j] = i.",
        "// Given an original logical position (k_inner=0..15, n_inner=0..15, n_tile_id=0..3)",
        "// inside a (k_tile_row, 1024) chunk, the post-permutation position is",
        "//   _PERM_INV[n_tile_id * 256 + k_inner * 16 + n_inner]",
        "//",
        "// 1024 ints = 4 KB; fits comfortably in __constant__ memory.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace q4k_q6k_marlin {",
        "",
        "__device__ __constant__ uint32_t c_PERM_INV[1024] = {",
    ]
    # 8 values per line, hex format for compactness.
    for chunk_start in range(0, 1024, 8):
        chunk = perm_inv[chunk_start:chunk_start + 8]
        lines.append("    " + ", ".join(f"{v:4d}" for v in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("} // namespace q4k_q6k_marlin")
    lines.append("")
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}  ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
